	1. First you need to install one metrics server which will fetch the required data.
	      wget -O metricserver.yml https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
   2. By this a yaml file will be downloaded apply this file an in kube-system namespace a pod will get created.
	3. Then create one deployment file as given in github file.
	4. Then apply one command as follows 
	      kubectl autoscale deployment mydeploy --cpu-percent=20 --min=1 --max=10
   5. By this command an HPA will be created with given specification.

kind: Deployment
apiVersion: apps/v1
metadata:
   name: mydeploy
spec:
   replicas: 1
   selector:
    matchLabels:
     name: deployment
   template:
     metadata:
       name: testpod8
       labels:
         name: deployment
     spec:
      containers:
        - name: c00
          image: httpd
          ports:
          - containerPort: 80
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
